import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  useAccount,
  useConnect,
  useDisconnect,
  useNetwork,
  useSwitchNetwork,
} from "wagmi";
import { InjectedConnector } from "wagmi/connectors/injected";
import { useEffect, useState } from "react";
import {
  shortenAddress,
  transformSymbol,
  numberWithCommas,
} from "../utils/utils";

export default function Home({ vaults }) {
  const [mounted, setMounted] = useState(false);
  const { address, isConnected } = useAccount();
  const { connect } = useConnect({
    connector: new InjectedConnector(),
  });
  const { disconnect } = useDisconnect();
  const { chain } = useNetwork();
  const { switchNetwork } = useSwitchNetwork();

  const depositedAmount = numberWithCommas(
    vaults
      .reduce((total, vault) => total + vault.deposited * vault.price, 0)
      .toFixed(2)
  );

  const OPTIMISM_VAULT_MANAGER = "0x30bb5A1858D1CfE22AF5E028F15dD8450E76FDc3";
  const ARBITRUM_VAULT_MANAGER = "0x305c0C5001f40D8fa21740d1D135Cdbb7Fd97C53";
  const XEARN = "0xed6229CD962413CbcF07C8f9DD8D30607157Fff7";

  const ARBITRUM_NODE_URI =
    "https://arb-mainnet.g.alchemy.com/v2/M4OMAtif3ZSHXjiTa0AT-lb_iKA0Lj3o"; // Plz don't use the api key
  const OPTIMISM_NODE_URI =
    "https://opt-mainnet.g.alchemy.com/v2/xhj3Bj3ukhHn3wUtCt76Bby0AmsUnmWp"; // Plz don't use the api key

  useEffect(() => {
    if (chain.id !== 137) {
      switchNetwork(137);
    }
  }, chain);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>xEarn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#00aba9" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>

      <p className={styles.warning}>
        Warning! This project is an experiment, it's not audited and DEFINITELY
        has vulnerabilities. If you want to deposit in any vault you see, go to{" "}
        <a
          href="https://yearn.finance/vaults"
          target="_blank"
          className={styles.yearn}
        >
          Yearn Finance
        </a>
      </p>

      <header className={styles.header}>
        <img
          src="/logo.png"
          alt="Logo"
          width="50"
          className={styles.logoHeader}
        />
        {mounted && isConnected ? (
          <span onClick={disconnect} className={styles.address}>
            {shortenAddress(address)}
          </span>
        ) : (
          <button className={styles.connect} onClick={connect}>
            Connect wallet
          </button>
        )}
      </header>

      <main className={styles.main}>
        <div className={styles.balances}>
          <div className={styles.deposited}>
            <p className={styles.balanceText}>Deposited</p>
            <b className={styles.balanceAmount}>${depositedAmount}</b>
          </div>
          <div className={styles.earnings}>
            <p className={styles.balanceText}>Earnings</p>
            <b className={styles.balanceAmount}>$0,00</b>
          </div>
        </div>

        <div className={styles.vaults}>
          <h2 className={styles.vaultsText}>All Vaults</h2>
          <table className={styles.table}>
            <thead>
              <tr>
                <th>Token</th>
                <th>APY</th>
                <th>Deposited</th>
                <th>TVL</th>
              </tr>
            </thead>
            <tbody>
              {vaults.map((row, index) => (
                <tr key={index} className={styles.tableRow}>
                  <td width="50%" className={styles.tokenRow}>
                    <img src={row.icon} alt={row.token} width="40px" />{" "}
                    <p className={styles.tokenText}>
                      {transformSymbol(row.token)}
                    </p>
                  </td>
                  <td>{row.apy}%</td>
                  <td className={row.deposited > 0 ? "" : styles.depositZero}>
                    {row.deposited.toFixed(2)}
                  </td>
                  <td>${numberWithCommas(row.tvl)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/chiin_rock"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with ✖ by Chiin
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const endpoints = [
    "https://api.yearn.finance/v1/chains/10/vaults/all",
    "https://api.yearn.finance/v1/chains/42161/vaults/all",
  ];

  const responses = await Promise.all(endpoints.map((url) => fetch(url)));
  const [data1, data2] = await Promise.all(responses.map((res) => res.json()));
  const combinedData = [...data1, ...data2];

  const vaults = combinedData
    .map((vault) => ({
      token: vault.token.symbol,
      icon: vault.token.icon,
      apy: (vault.apy.net_apy * 100).toFixed(2),
      deposited: Math.random() > 0.5 ? 10 : 0,
      price: vault.tvl.price,
      tvl: vault.tvl.tvl.toFixed(0),
    }))
    .filter((vault) => parseFloat(vault.tvl) > 0);

  const uniqueVaults = vaults.reduce((acc, vault) => {
    const existingVault = acc.find((v) => v.token === vault.token);

    if (existingVault) {
      if (parseFloat(vault.tvl) > parseFloat(existingVault.tvl)) {
        const index = acc.indexOf(existingVault);
        acc[index] = vault;
      }
    } else {
      acc.push(vault);
    }

    return acc;
  }, []);

  uniqueVaults.sort((a, b) => parseFloat(b.apy) - parseFloat(a.apy));

  return {
    props: {
      vaults: uniqueVaults,
    },
  };
}
